### PR TITLE
Added haptics.

### PR DESCRIPTION
**Pull request by FlyN-Nick**

### CODE REVIEW

**Comment by Jemoka** [comment]
I remember there being an impact style that’s like DumDUMP (read: twice, lighter then heavier)! Which is better than the one-tap of light. I think its called Notification or Alert or something, and is not in the same line as the light/medium/heavy styles

**Comment by Jemoka** [comment]
looks good; though will approve when CI is back so that you could merge to a beta.

**Review by Jemoka — APPROVED** [review]
If its the wrong ge-donk I will be disappointed :)

**Review by zbuster05 — APPROVED** [review]
it *better* be the right gadunk

**Pull request merged**
