### PR TITLE
Dev project completion

### LINKED ISSUE #131: FEAT completeable projects
**Is your feature request related to a problem? Please describe.**
Projects don't disappear when its contents are all completed.

**Describe the solution you'd like**
Being able to do so, perhaps as a toggle.

**Additional context**
A la OmniFocus, from [quantumish#3800](https://discordapp.com/channels/691409213653778444/723796928739016704/737695167678644264)

### PR DESCRIPTION
**Pull request by zbuster05**
Projects can now complete/archive. Closes #131.

### CODE REVIEW

**Comment by Jemoka** [comment]
@zbuster05 could you edit the message to include the words "Closes #131"? It will automate so that the corresponding issue gets closed.

**Comment by zbuster05** [comment]
> @zbuster05 could you edit the message to include the words "Closes #131"? It will automate so that the corresponding issue gets closed.

Done.

**Review by Jemoka — CHANGES_REQUESTED** [review]
Sorry. need changes

**Review by TheEnquirer — DISMISSED** [review]
this code is so good omg oh my god admins could edit stuff

**Comment by zbuster05** [comment]
> I am putting this here just to force one of you to pull it down and test it once

Unnecessary, @TheEnquirer already agreed to do so before review

**Review by Jemoka — CHANGES_REQUESTED** [review]
image

nope. sorry

**Review by Jemoka — APPROVED** [review]
I love it

**Comment by Jemoka** [comment]
Good job team.

**Pull request merged**
