### PR TITLE
ABTIB improvements

### PR DESCRIPTION
**Pull request by Exr0n**
- assume date comes after current date in ABTIB
- parse project name if the intention ends in 'for (.+)'

I have NO CLUE how the submodules work... so this PR might be fricked.
Improves #187 and solves #228.

### CODE REVIEW

**Review by Jemoka — CHANGES_REQUESTED** [review]
Submodules still fricked. CI failed. Please ensure that your submodules are in order before merging. Let me know if you need help.

**Comment by Exr0n** [comment]
wait what I can just edit your comment??

also, I think I fixed the submodules. That should only apply to CondutionEngine... how to debug?

**Comment by Jemoka** [comment]
> wait what I can just edit your comment??
> 
> also, I think I fixed the submodules. That should only apply to CondutionEngine... how to debug?

nope. Just reran smoke test and CI still failed.

**Review by Jemoka — APPROVED** [review]
🥂 Cheers! Welcome back aboard.

**Review by zbuster05 — APPROVED** [review]

**Pull request merged**
