### PR TITLE
Dev fixtagspaney

### PR DESCRIPTION
**Pull request by zbuster05**
Fixed y on tags pane

### CODE REVIEW

**Review by TheEnquirer — APPROVED** [review]
why is this code so much better than the last pr?

**Comment by zbuster05** [comment]
> why is this code so much better than the last or?

Shaking my head

**Review by Jemoka — APPROVED** [review]
so is @zbuster05 merging this?

**Comment by Exr0n** [comment]
ooo can i hit the button

**Comment by Jemoka** [comment]
Sure, why not? ;)

**Pull request merged**
