### PR TITLE
Beta v0.1.3

### PR DESCRIPTION
**Pull request by Jemoka**
<h1>This. Is. Beta v0.1.3</h1>

## Release Notes
You will realize that the bundle number of this build is `v0.1.3-beta2` but not! beta1. Why is that, you ask? Beta1 had some stability improvements and other general drag ghosting prevention, but it ended up being so buggy that I didn't even bring it to the team for final approval. Beta2 addresses the issues, amount others: some color changes, project filters in perspective recursive bug fixes (DFS, booya!), etc. This is probably what we show on the keynote. 

Side note: like any project with a database solution behind it, we need money to keep it running. This is why we have launched a Patreon page [here](https://www.patreon.com/condution) for anyone and everyone that wants to support this project.

## Things that you could enjoy today

1. Task creation/destruction
2. Project creation/destruction
3. Tag creation/destruction
4. Main window, due soon, and coloring
5. Task/project sorting
6. Parallel and sequential projects
7. Repeating tasks
8. Perspectives <= documentation on the filter syntax!
9. Mostly bugless natural language input on quick-add and task due dates
10. Advanced perspective filtering for remaining and available tasks, sort perspectives by their due date
11. Dragging tasks into projects and subprojects
12. Bug fixes
13. Performance things!
14. Better Artwork Courtesy of Lynn Yang
15. Better repeating tasks
16. Stability, stability, stability (with significant performance improvements!)

## Things that you will be able to enjoy
These are the features yet to be implemented that will be implemented hopefully in the near future (keep in mind that we have a great deal more features in store for all of you).

- [ ] A universal search bar
- [ ] A settings page, for sure says @zbuster05 and @TheEnquirer 

## People that you should thank
@Exr0n @zbuster05  @TheEnquirer @Ban-Ironic-Ohms (and Lynn Yang the designer, but she doesn't have a Github account) (and I guess myself @Jemoka )

Hopefully, you are now free to be productive people with fewer bugs

With :heart:s and :green_salad:s from everyone at #!/Shabang

### CODE REVIEW

**Comment by Jemoka** [comment]
> Is there a next button?

what do you mean? The daterow is not going out on 0.1.3

**Comment by Exr0n** [comment]
Also @Jemoka why does it say "and i guess myself also @ zbuster05" in the pr comment?

**Comment by Jemoka** [comment]
> Also @Jemoka why does it say "and i guess myself also @ zbuster05" in the pr comment?

Whoops I copied Zach's template? 😏 Fixing it now

**Comment by Exr0n** [comment]
Wait where's @TheEnquirer 's approval? I got an email about it... did he approve the wrong thing?

**Comment by Jemoka** [comment]
> Wait where's @TheEnquirer 's approval? I got an email about it... did he approve the wrong thing?

There's *two* 😲 PRs going out today. One is this one, a housekeeping merge into master for a release branch, and #41, which is the daterow.

**Comment by Jemoka** [comment]
In other news, 🌾 github markdown emojis are fun

**Pull request merged**
