### PR TITLE
Dev updatingdependencies

### PR DESCRIPTION
**Pull request by zbuster05**
Updating dependencies that had security vulnerabilities.

### CODE REVIEW

**Review by Jemoka — CHANGES_REQUESTED** [review]
It's good, but can we please try getting capacitor not crashing on build, too?

**Review by Jemoka — APPROVED** [review]
Nevermind. I am blind to `beta-v1.1.0`. My bad.

**Review by TheEnquirer — COMMENTED** [review]
could be better.

**Review by TheEnquirer — APPROVED** [review]
jk

**Pull request merged**
