### PR TITLE
Dev localization

### PR DESCRIPTION
**Pull request by zbuster05**
Setting up localization infrastructure

### CODE REVIEW

**Comment by Jemoka** [comment]
@zbuster05 
image

**Comment by zbuster05** [comment]
> @zbuster05
> image

Conflicts have been resolved. Haven't pulled it down to test it yet, but the conflicts were in the Completed.jsx file, so if you want to go ahead and test it instead feel free.

**Comment by Jemoka** [comment]
I will get to it tonight. Before then, @TheEnquirer or @Exr0n or @Ban-Ironic-Ohms take a look?

**Comment by Exr0n** [comment]
@Jemoka you want me to actually look at it? or just hit the button? because I don't know the code base anymore..

**Review by Ban-Ironic-Ohms — APPROVED** [review]

**Pull request merged**
