### PR TITLE
A first interaction ui

### PR DESCRIPTION
**Pull request by Jemoka**
This:
Screen Shot 2020-11-26 at 9 00 12 PM

Sexy, right?

### CODE REVIEW

**Review by TheEnquirer — APPROVED** [review]
jack ngl i kinda liked the simplicity of the old one better. having to complete a task was very elegant

**Comment by Jemoka** [comment]
Oh you still get to complete a task on the sign up process ;)

**Comment by Jemoka** [comment]
But ok, hmmm. Maybe we could do it, but let's talk later

**Comment by Ban-Ironic-Ohms** [comment]
I like the new one, it is easier to see

**Pull request merged**
